object Versions {
    const val kotlin = "1.7.0"
    const val hilt = "2.41"
    const val architecture = "2.4.1"
    const val retrofit = "2.9.0"
    const val coroutines = "1.5.2"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val loggingInterceptor = "4.9.1"
    const val jUnit = "4.13.2"
    const val room = "2.4.2"
    const val roomPaging = "2.5.0-alpha01"
    const val glide = "4.12.0"
    const val paging = "3.1.1"
    const val activityKtx = "1.3.1"
    const val navigation = "2.5.0"
    const val liveData = "2.5.0"
    const val hiltNavigation = "1.0.0"
    const val dataStore = "1.0.0"
}